spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pizzeria
    username: k3ras
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        security:
          web:
            debug
