spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pizzeria
    username: k3ras
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
